### ISSUE TITLE
Automatic updates

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/pySolo-Video#24]
It should be possible to update nodes and devices with the latest stable version of their respective software.

This implies direct/indirect connection to the internet, at least, from the node, so @PolygonalTree  we need to discuss this. For instance, can we connect to AUR from all devices, or do we need to e.g. send a tarball and ask them to install it (the latter being obviously v dirty :()

**Comment by ggilestro** [comment]
I would not use AUR for the updates but a custom PKG repository somewhere on the internet. 
A possible pipeline:

1. We setup a web server or ftp server acting as custom repo - it's pretty straight forward to setup with `repo-add` and we can put it on the pysolo.net servers
2. The node is configured to use our custom repo and *no other* repo (not even the officiale arch)
3. The node is configured to run a  `pacsrv -Syyu --noconfirm` at boot if the internet is detected
4. Because we use `pacsrv` instead of `pacman` the node will sync the distant repo locally (see https://wiki.archlinux.org/index.php/Pacserve )
5. The updated node is replugged to the local network
6. The videomonitors are configured to use the node as repo and will issue a `pacman -Syyu --noconfirm` at every boot

**Comment by qgeissmann** [comment]
I like this, but this involves the node being capable on connecting to the net at some, right?
In ICL, this would require manually registering the device's MAC address, which the user will not be able to do. Maybe we can discuss that tomorrow/friday.
In any case, it would be nice to have real life testing platform (router + node + device) at some point soon.

**Comment by PolygonalTree** [comment]
I was considering to create an admin interface in the website to configure the Node: That means that MAC address will be printed in that page and also you can check if there is internet connection.
I have to figure out how to deal with two interfaces in the node:
1. Wifi interface to connect to the router and therefore the devices (SM/SD). 
2. Ethernet connection to the campus internet as a normal computer. 
Updates will come from the Ethernet connection to the node and from there to the Attached Devices.

**Comment by ggilestro** [comment]
Yes. This prompts two suggestions:

1. @PolygonalTree , make sure a label with the node MAC address is present and visible on the case. This way any IT department can authorize the machine on the network if this is needed

2. We may be able to use a USB thumbdrive as source of the packages to be installed. In this scenario the user plugs a thumbdrive to the node, the node mounts it and scans it for *.tar.gz and installs everything with a pacman -U *.tar.gz 

I think the option of having the node occasionally connected on the internet just for updates/remote assistance (btw, make sure SSHD is running) is the best option and a fair compromise

**Comment by qgeissmann** [comment]
We use git/ bare git repo on node for update. So closing this issue. Related issues #53 #52
