### ISSUE TITLE
broken link in web interface

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/pySolo-Video#89]
In the list of devices, the link to one device is e.g.:

`http://192.169.123.1/#sm%2F00036dfce6e94dee9bb1a845281b086e`

instead of 

`http://192.169.123.1/#sm/00036dfce6e94dee9bb1a845281b086e`

When the former is clicked, the user (on firefox) need to reload the page (F5) in order to see the device.

**Comment by PolygonalTree** [comment]
Cannot "fake" a device_Server because of this error:
No handlers could be found for logger "dummy", where is this handler?

**Comment by qgeissmann** [comment]
`src/pysolovideo/web_utils/helpers.py:    log = logging.Logger("dummy")`

**Comment by PolygonalTree** [comment]
Cannot "fake" a device_Server because of this error:
No handlers could be found for logger "dummy", where is this handler?

**Comment by PolygonalTree** [comment]
The problem is not there, further investigation shows this error when trying to run device_server.py:
2015-04-14 13:46:30,892 device_server.py, 181, <module>: Traceback (most recent call last):
  File "device_server.py", line 178, in <module>
    run(api, host='0.0.0.0', port=port, server='cherrypy', debug=True)
  File "/data1/virtual_environmets/psvnode/lib/python2.7/site-packages/bottle.py", line 3105, in run
    _stderr("Bottle v%s server starting up (using %s)...\n" % (__version__, repr(server)))
ValueError: I/O operation on closed file
_stderr is sys.stderr.write.
Any ideas?

**Comment by PolygonalTree** [comment]
OK, you can start device_server.py only if the option quiet=True is enabled. Otherwise the previous error stops bottle.

**Comment by PolygonalTree** [comment]
I can not replicate the problem in the link. Seems correct to me. Be in mind that it opens in a new tab and if you have already open the tab with that sleep monitor it won't change the tab automatically.

**Comment by PolygonalTree** [comment]
Solved by a4fee26
