### ISSUE TITLE
Node crashes if connection stops whilst downloading large file

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/pySolo-Video#97]
Was downloading a large file. Connection was interrupted. could not connect to the node back
Related to #74

**Comment by PolygonalTree** [comment]
Maybe related with this:
http://stackoverflow.com/questions/11866792/how-to-prevent-errno-32-broken-pipe

**Comment by PolygonalTree** [comment]
Here possible solution, catching the error on the download function. http://stackoverflow.com/questions/180095/how-to-handle-a-broken-pipe-sigpipe-in-python/180922#180922

**Comment by PolygonalTree** [comment]
Other possible solution, is Request library a urllib2 with steroids. http://stackoverflow.com/questions/16694907/how-to-download-large-file-in-python-with-requests-py

**Comment by qgeissmann** [comment]
btw? you think, at the moment, the file is copied in memory before upload? if yes, this is a clear issue... e.g. i had a 700MB zip to dl for 4 days x 4 devices

**Comment by PolygonalTree** [comment]
I have made some test and I tried to download a file of 1.3Gb directly from Node. It worked with no errors. I also tried to kill the connection on the middle of the transaction and the transaction stops without problem, Node does not hang. 
I have also checked the memory during transaction and Node is not loading the file on memory before it serves it.
So not really sure where the problem is. Do you have more info?

**Comment by qgeissmann** [comment]
This issue was moved to gilestrolab/ethoscope#6
